language: node_js
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=development
  matrix:
    secure: dFeUAREMY0o78K7g12NoHyGm/I3CR4Koq5K0Top5hv4+yRkUuuoFIfoVYQMb7uRtBwL614ibw2h1wh8mt9K/eB27mFz5lp3FGGP/J82pAweLxmeH8Hc+Gjz96N1ZgHxzH4crY6bzhg0M4RtPe0L/qfgVVKNZyXO7H7V68G+Dfz7OAqNhebe2uyJubVd2XhYshPwUYWRZUeX/AZpZjBJSymXx71QrCebwOnJsz3WSzrFBmQNsXd2z+cbBZLl53RE9hXMyBReZwXN5Q8udk5scquPAXw5tBgXYffeQEJlI+efUyr8+eGoZXAnw/857LOEb1d6l5XIglFOi7h5irHweMtayThx8To5bd+YQru7+/l3Ox7ExFehC2sWn6N8UQuQ05IgeFdnGyPRYJQJQT2gyOE0uP5GAWOR8zM3OA+KALPMZBnB4tm1Mmo5++NuD/r+rwHI4ouxewB91kAQaGBslNe+dYrSke3iGTFBeLATwNwbjA71Kn21ffXoNi0nlY20zvyI9PyIxakCI0zrInobGBtngozwtYZTu0X8ubkKU4V5evHf7Z8QkbGbQe0BokT86HKV3SWZsTZdvD1FLIXA17REVuwPzWokcU8dEL50rJX7k8ZUa+4o9jA413tL4uykZ0taRssXi7WfXltk4SCS1UNtbYYMjtXYp7ziR1jxwKMY=
install:
- npm install
before_script:
- |
  if [ "$TRAVIS_BRANCH" = master ]; then
    echo "Starting production build"
    export NODE_ENV="production"
  elif [ "$TRAVIS_BRANCH" = staging ]; then
    echo "Starting staging build"
    export NODE_ENV="staging"
  fi
- npm run lint
- npm run test
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: ad457e5bf95c9ba11df640b974a49c221a7956eb
  on:
    all_branches: true
